export const SIGNUP_WITH_EMAIL_REQUEST = "SIGNUP_WITH_EMAIL_REQUEST";
export const SIGNUP_WITH_EMAIL_SUCCESS = "SIGNUP_WITH_EMAIL_SUCCESS";
export const SIGNUP_WITH_EMAIL_FAILURE = "SIGNUP_WITH_EMAIL_FAILURE";

export const LOGIN_WITH_EMAIL_REQUEST = "LOGIN_WITH_EMAIL_REQUEST";
export const LOGIN_WITH_EMAIL_SUCCESS = "LOGIN_WITH_EMAIL_SUCCESS";
export const LOGIN_WITH_EMAIL_FAILURE = "LOGIN_WITH_EMAIL_FAILURE";
